### ISSUE TITLE
Why not use apollo-server-micro?

### ISSUE THREAD

**Issue by crisu83** [Saeris/apollo-server-vercel#10]
I've used apollo-server-micro in the past to run Apollo Server on Vercel:
https://github.com/vercel/next.js/blob/canary/examples/api-routes-apollo-server/pages/api/graphql.js

How does using this library differ from that? Are there any added benefits?

**Comment by Saeris** [comment]
There's not a whole lot different between the two,. This implementation is built directly on top of Vercel's serverless function request/response signature, so there's no need to add another server framework like Micro on top of it to handle graphql requests.

At the time when I put this library together, it was unclear what was the correct way to use GraphQL with Vercel functions, so I had set out to solve that for myself.

Of the top of my head I don't know if there's much of a benefit to using this library over `apollo-server-micro`, other than that it should have a lighter footprint.

**Comment by bkensey** [comment]
@Saeris Unfortunately it seems like the correct way to use Graphql as a serverless route is unclear. See https://github.com/apollographql/apollo-server/issues/5547. I've spent a few days this week mucking about and trying to get `apollo-server-micro` and `apollo-server-lambda` working, but the micro version kept throwing errors and I wasn't a huge fan of having to start() the server before calling createHandler(). The lambda version had almost no useful documentation or blog posts and no TypeScript support to boot.

Your library was pretty easy to drag and drop in, and I'm grateful for the work you've done. I'm hoping the Apollo team can find some time, per that github thread, to put some thought into how apollo-server should work on the vercel platform.
