### ISSUE TITLE
Intent to ship: v2

### ISSUE THREAD

**Issue by Saeris** [Saeris/apollo-server-vercel#12]
Hey all! Thanks for taking an interest in this little hobby project of mine!

After a long period of inactivity, I finally did some cleanup and updating, publishing the first major version. Often when I publish libraries, I don't intend to support them, rather I'm sharing my code so that others can fork it or learn from it. This library is no different, and so that's why it's taken forever for me to come back and publish an update. By using a major version, I hope I'm not accidentally breaking any of your projects and have given you a clear boundary of before and after.

That said, publishing 1.0.0 is really just a stop-gap measure. I wanted to get some fixes in for long-standing issues before doing any more work on the project. For all intents and purposes, the v1 branch is now entirely unsupported and will only be around for use with Apollo Server v2 environments.

Now I want to get to work on v2.0.0, which will bump up everything to latest and officially adopt Apollo Server 3. I don't plan on supporting backwards compatibility any more than what `apollo-server-core` already enables, so if you want to adopt the next major version, you'll need to keep all of this in mind.

There won't be any release timeframe. It'll ship when it's done, and development will be driven by my own personal needs as always. Going forward, I strongly encourage you to fork this repo if you intend to use this library in production.

**Comment by apuyou** [comment]
Hi @Saeris!

I've been using Apollo & Next.js for some time and was using the micro integration as per the docs. This broke when updating to Next.js 12 and I assembled a small custom integration to fix this (https://github.com/apuyou/apollo-server-nextjs).

I just came across your project which looks great and has been around for much longer, so congratulations on this!

Are you still planning on working on an Apollo Server v3 compatible version? I'd be happy to help and also merge everything into a single project which would probably be simpler for everyone.

**Comment by Saeris** [comment]
Hey thanks for reaching out!

At some point I'll likely update this to suit my own needs. Presently I'm not working on any projects that require Apollo Server, so I haven't needed to use or maintain this integration. My guess is that at some point I will need an updated version, but at this time I don't know when that will be.

So, if you have a need for an v3 compatible integration, I'd say move forward with publishing your own library.

I appreciate the thoughtfulness of wanting to merge efforts and simplify discovery for the community, however I also want to be forthright about my lack of desire to maintain this codebase for others, hence why I encourage anyone interested in this repo to fork it.

**Comment by apuyou** [comment]
Okay, many thanks for the quick update!

**Comment by Saeris** [comment]
Closing this out now as there's actually an official integration which can be found here: https://github.com/apollo-server-integrations/apollo-server-integration-next#readme as mentioned in #15
