### ISSUE TITLE
404 when using GET method 

### ISSUE THREAD

**Issue by irfan-maulana-tkp** [Saeris/apollo-server-vercel#7]
I try to hit the endpoint using GET method but got 404.

This is example how to hit the query using GET:

```js
const gqlQuery = `query hello {
  hello
}`;

fetch(`https://apollo-server-vercel.saeris.io/api/example?query=${encodeURIComponent(JSON.stringify(gqlQuery))}`, {
  credentials: 'omit',
  headers: { 'Content-Type': 'application/json' },
  method: 'GET',
})
  .then((res) => res.json())
  .then((res) => console.log('Response from server', res));
```

After some digging, I think it because of https://github.com/Saeris/apollo-server-vercel/blob/master/src/vercelApollo.ts#L28
The body is not `falsy` but an empty object `{}`, so it will never read the `req.query`.

Maybe you can add a method checking before getting the query:

```js
// use req.body only if the method is POST
query: req.method === `POST` ? req.body : req.query,
```

**Comment by Saeris** [comment]
Good catch! I'll get a fix in and a new version published/deployed later today. Thanks for the heads up and for suggesting a solution!

**Comment by Saeris** [comment]
Just wanted to follow up, a lot of my time got eaten up by a big project at work so this fell off my radar.

I had started work on adding your suggested changes and in the process I also got started on overhauling the test suite. There were some unexpected complications there and I just haven't had the time to resolve them.

Will try to get back to this soon. Sorry to keep you waiting!

**Comment by mazipan** [comment]
No problem, not urgent at all.
Take your time 👍
Just with enabling GET request, we can cache the request easier on the client side
