### ISSUE TITLE
CORS config won't apply to the response

### ISSUE THREAD

**Issue by tomouchuu** [Saeris/apollo-server-vercel#8]
The CORS options are applied to the OPTIONS call before requests are made but then aren't applied on the actual request. I fixed this by adding the 
```js
setHeaders(res, _objectSpread({
    "Content-Type": `application/json`
}, requestCorsHeadersObject));
```
from the server-health responses to the `fileUploadHandler()` here: https://github.com/Saeris/apollo-server-vercel/blob/master/src/ApolloServer.ts#L178-L183

Not sure if this knocks out the file upload stuff but I'm getting responses back with the correct headers now.

I should have sometime later in the week to contribute a PR if this is the way to go or is there a better solution you have in mind?

**Comment by Saeris** [comment]
If you'd like to open a PR for this I'd appreciate it! As soon as I can spare some time from work, I'll review it and get it merged asap.
